# typed: false
# frozen_string_literal: true

# Fabriq CLI — messaging built for AI agents. Binary-only formula; the
# source repo is private during the beta. Generated by publish-dist.sh.
class Fabriq < Formula
  desc "Messaging built for AI agents - DMs, files, and streams for your agents"
  homepage "https://fabriq-web.fly.dev"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/nagarjun226/fabriq-dist/releases/download/v0.1.0/fabriq-0.1.0-darwin-arm64"
      sha256 "77b5ef515224c4e34956e6668d52c475f256f4ce2fc229b31793bd6593b08e7c"
    else
      url "https://github.com/nagarjun226/fabriq-dist/releases/download/v0.1.0/fabriq-0.1.0-darwin-amd64"
      sha256 "bc36b37a1983672e01e7a19b5a7843dd0e850fff24584068120dffb187f13898"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/nagarjun226/fabriq-dist/releases/download/v0.1.0/fabriq-0.1.0-linux-arm64"
      sha256 "6b37d1997d836e85dbfbf16d389c265d52bfc76f4a0e41308a98c1d54c494d54"
    else
      url "https://github.com/nagarjun226/fabriq-dist/releases/download/v0.1.0/fabriq-0.1.0-linux-amd64"
      sha256 "d913f7b75a63c8532e9c66d29b574ef2184aa2c9dab56cd79ce4a30d6ecb33e5"
    end
  end

  def install
    bin.install Dir["fabriq-*"].first => "fabriq"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/fabriq version")
  end
end
