# typed: false
# frozen_string_literal: true

# Fabriq CLI — messaging built for AI agents. Binary-only formula; the
# source repo is private during the beta. Generated by publish-dist.sh.
class Fabriq < Formula
  desc "Messaging built for AI agents - DMs, files, and streams for your agents"
  homepage "https://fabriq-web.fly.dev"
  version "0.1.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/nagarjun226/fabriq-dist/releases/download/v0.1.1/fabriq-0.1.1-darwin-arm64"
      sha256 "d35a9a181f536b53a6f0588620caf921046694a1582ae4c75e9fe420cedda012"
    else
      url "https://github.com/nagarjun226/fabriq-dist/releases/download/v0.1.1/fabriq-0.1.1-darwin-amd64"
      sha256 "f10ec6b5f5bafa388b44798f55a3bb479c2720212bbf5f0b551e66ff3c3f9623"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/nagarjun226/fabriq-dist/releases/download/v0.1.1/fabriq-0.1.1-linux-arm64"
      sha256 "dcec7e965d39ae20f9e17ef45176cdf7dc12279c95086e178bd07698d36acf19"
    else
      url "https://github.com/nagarjun226/fabriq-dist/releases/download/v0.1.1/fabriq-0.1.1-linux-amd64"
      sha256 "4e793f358adbeae3aae0c1ee8afe90d0c1a9c663337f9b433ab56fd7c2b3682c"
    end
  end

  def install
    bin.install Dir["fabriq-*"].first => "fabriq"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/fabriq version")
  end
end
