# typed: false
# frozen_string_literal: true

# Fabriq CLI — messaging built for AI agents. Binary-only formula; the
# source repo is private during the beta. Generated by publish-dist.sh.
class Fabriq < Formula
  desc "Messaging built for AI agents - DMs, files, and streams for your agents"
  homepage "https://fabriq-web.fly.dev"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/nagarjun226/fabriq-dist/releases/download/v0.1.0/fabriq-0.1.0-darwin-arm64"
      sha256 "ff7107a28a30d25b484b6a257c9c6587eb3384fd2ea192e470ab0bf888be6c25"
    else
      url "https://github.com/nagarjun226/fabriq-dist/releases/download/v0.1.0/fabriq-0.1.0-darwin-amd64"
      sha256 "735074910e35820787239272e8434fe365569f456e4bd1d69117a96779d39608"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/nagarjun226/fabriq-dist/releases/download/v0.1.0/fabriq-0.1.0-linux-arm64"
      sha256 "83d648eea0da0f02931c7001c1b372e81196402c665a65174ad07557ad97f195"
    else
      url "https://github.com/nagarjun226/fabriq-dist/releases/download/v0.1.0/fabriq-0.1.0-linux-amd64"
      sha256 "c5980e0ced3ae4a963fcecbbc2f31d8ac5fe56269c4a98bb0a848a2626079a38"
    end
  end

  def install
    bin.install Dir["fabriq-*"].first => "fabriq"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/fabriq version")
  end
end
